In [1]:
# Imports
import requests
import pandas 
import numpy as np

In [2]:
# Get data "
Year = "2020"
r = requests.get("https://www.baseball-reference.com/register/team.cgi?id=e1b4d4c9")

In [3]:
############################################
# Clean data [ANDY IS A FUCKING GENIOUS!]
string = r.text
string = string.replace ("-->","")
string = string.replace ("!--","")

############################################
#DF = data frame (PANDAS)
dfs = pandas.read_html(string)
# get DF 0
Bat = dfs[0]
# Dead code, but example of where clause
#Bat["Rk"] = np.where(Bat['Rk']=NaN, "TeamBat",df['Rk'])
Bat['Rk'].fillna("TeamBat", inplace=True)
Bat.sort_values(by=['BA'], ascending=True, inplace=True)
Bat

,Rk,Name,Age,G,PA,AB,R,H,2B,3B,...,OBP,SLG,OPS,TB,GDP,HBP,SH,SF,IBB,Notes
21,22,Shosei Togo,20.0,2,4,4,0,0,0,0,...,0.000,0.000,0.000,0,0,0,0,0,0,NaN
5,6,Seiji Kobayashi,31.0,2,5,3,1,0,0,0,...,0.400,0.000,0.400,0,0,2,0,0,0,NaN
6,7,Takuya Kuwahara,24.0,4,1,1,0,0,0,0,...,0.000,0.000,0.000,0,0,0,0,0,0,NaN
20,21,Shunta Tanaka*,26.0,4,2,2,0,0,0,0,...,0.000,0.000,0.000,0,0,0,0,0,0,NaN
15,16,Angel Sanchez,30.0,3,6,5,0,0,0,0,...,0.000,0.000,0.000,0,0,0,1,0,0,NaN
26,27,Dai Yuasa,20.0,5,6,5,1,0,0,0,...,0.000,0.000,0.000,0,0,0,1,0,0,NaN
14,15,Toshiki Sakurai,26.0,2,5,5,0,0,0,0,...,0.000,0.000,0.000,0,0,0,0,0,0,NaN
8,9,Daiki Masuda,26.0,13,19,15,7,2,1,0,...,0.316,0.200,0.516,3,0,0,0,0,0,NaN
23,24,Zelous Wheeler,33.0,6,14,12,0,2,0,0,...,0.286,0.167,0.452,2,0,0,0,0,0,NaN
17,18,Tomoyuki Sugano,30.0,3,8,6,0,1,0,0,...,0.167,0.167,0.333,1,0,0,2,0,0,NaN
25,26,Naoki Yoshikawa*,25.0,15,38,35,2,7,0,0,...,0.263,0.286,0.549,10,1,0,0,0,1,NaN
22,23,Akihiro Wakabayashi#,26.0,9,5,5,3,1,0,0,...,0.200,0.200,0.400,1,0,0,0,0,0,NaN
7,8,Yoshihiro Maru*,31.0,16,67,61,6,13,3,0,...,0.284,0.410,0.693,25,1,0,0,0,0,NaN
0,1,Cristopher Crisostomo*,26.0,3,5,4,0,1,0,0,...,0.250,0.250,0.500,1,0,0,1,0,0,NaN
10,11,Takumi Ohshiro*,27.0,13,39,32,6,8,1,1,...,0.385,0.344,0.728,11,0,0,0,0,2,NaN
27,TeamBat,27 Players,29.5,16,603,529,84,139,26,2,...,0.347,0.433,0.780,229,12,3,6,0,7,NaN
9,10,Hiroyuki Nakajima,37.0,16,57,45,4,12,3,0,...,0.421,0.467,0.888,21,2,0,0,0,0,NaN
24,25,Daikan Yoh,33.0,13,31,30,8,8,1,0,...,0.290,0.400,0.690,12,1,0,0,0,0,NaN
2,3,Yoshiyuki Kamei*,37.0,12,32,26,3,7,4,0,...,0.406,0.423,0.829,11,0,1,0,0,0,NaN
13,14,Hayato Sakamoto,31.0,15,64,55,11,15,2,1,...,0.375,0.509,0.884,28,3,0,0,0,2,NaN
16,17,Shinnosuke Shigenobu*,27.0,13,16,14,6,4,1,0,...,0.375,0.571,0.946,8,0,0,0,0,0,NaN
12,13,Gerardo Parra*,33.0,15,57,52,7,15,2,0,...,0.351,0.500,0.851,26,0,0,0,0,1,NaN
1,2,Shingo Ishikawa,27.0,12,10,10,1,3,0,0,...,0.300,0.600,0.900,6,0,0,0,0,0,NaN
18,19,Ginjiro Sumitani,32.0,8,20,18,2,6,1,0,...,0.368,0.389,0.757,7,1,0,1,0,0,NaN
4,5,Takumi Kitamura,24.0,10,15,13,2,5,2,0,...,0.467,0.538,1.005,7,0,0,0,0,0,NaN
11,12,Kazuma Okamoto,24.0,16,68,62,14,24,4,0,...,0.441,0.694,1.135,43,2,0,0,0,1,NaN
19,20,Kazuto Taguchi*,24.0,3,6,6,0,3,1,0,...,0.500,0.667,1.167,4,0,0,0,0,0,NaN
3,4,Yukinori Kishida,23.0,2,3,3,0,2,0,0,...,0.667,0.667,1.333,2,1,0,0,0,0,NaN

In [4]:
Pitch = dfs[1]
Pitch['Rk'].fillna("TeamPitch", inplace=True)
#Pitch.sort_values(by=['ERA'], ascending=True, inplace=True)
#Strip * from end of text
Pitch["Name"] = Pitch["Name"].str.strip("*") 
Pitch

,Rk,Name,Age,W,L,W-L%,ERA,G,GS,GF,...,BK,WP,BF,WHIP,H9,HR9,BB9,SO9,SO/W,Notes
0,1,Cristopher Crisostomo,26.0,0,2,0.000,4.11,3,NaN,NaN,...,0,0,66,1.304,10.0,2.3,1.8,7.6,4.33,NaN
1,2,Rubby De La Rosa,31.0,0,0,NaN,1.80,6,NaN,NaN,...,0,1,20,1.200,9.0,1.8,1.8,5.4,3.00,NaN
2,3,Takahiro Fujioka,30.0,0,0,NaN,3.18,6,NaN,NaN,...,0,1,27,1.765,9.5,1.6,6.4,4.8,0.75,NaN
3,4,Yuri Furukawa,24.0,0,0,NaN,4.50,1,NaN,NaN,...,0,0,9,2.000,18.0,4.5,0.0,9.0,NaN,NaN
4,5,Hayato Horioka,21.0,0,0,NaN,0.00,1,NaN,NaN,...,0,0,6,0.500,4.5,0.0,0.0,9.0,NaN,NaN
5,6,Yohei Kagiya,29.0,0,0,NaN,3.86,7,NaN,NaN,...,0,0,16,0.643,3.9,0.0,1.9,5.8,3.00,NaN
6,7,Takuya Kuwahara,24.0,1,0,1.000,4.50,4,NaN,NaN,...,0,0,25,1.167,6.0,0.0,4.5,7.5,1.67,NaN
7,8,Ryosuke Miyaguni,28.0,0,0,NaN,5.40,6,NaN,NaN,...,0,0,29,1.350,9.5,1.4,2.7,8.1,3.00,NaN
8,9,Kota Nakagawa,26.0,0,0,NaN,1.29,7,NaN,NaN,...,0,0,28,1.000,6.4,0.0,2.6,6.4,2.50,NaN
9,10,Toshiki Sakurai,26.0,1,0,1.000,1.93,2,NaN,NaN,...,0,0,52,0.714,5.1,1.3,1.3,9.0,7.00,NaN
10,11,Angel Sanchez,30.0,2,1,0.667,2.63,3,NaN,NaN,...,0,0,61,1.610,8.6,0.7,5.9,2.6,0.44,NaN
11,12,Hirokazu Sawamura,32.0,1,1,0.500,7.50,8,NaN,NaN,...,0,0,28,1.667,7.5,0.0,7.5,9.0,1.20,NaN
12,13,Tomoyuki Sugano,30.0,2,0,1.000,2.91,3,NaN,NaN,...,0,0,83,0.831,5.8,0.8,1.7,9.6,5.75,NaN
13,14,Kazuto Taguchi,24.0,1,0,1.000,2.08,3,NaN,NaN,...,0,1,52,1.077,7.6,0.7,2.1,6.2,3.00,NaN
14,15,Kyosuke Takagi,30.0,0,1,0.000,6.00,10,NaN,NaN,...,0,0,25,1.167,10.5,1.5,0.0,15.0,NaN,NaN
15,16,Shosei Togo,20.0,2,0,1.000,2.77,2,NaN,NaN,...,0,1,50,1.000,5.5,0.7,3.5,7.6,2.20,NaN
16,17,Thyago Vieira,26.0,0,0,NaN,0.00,2,NaN,NaN,...,0,0,10,4.500,20.3,0.0,20.3,0.0,0.00,NaN
17,TeamPitch,17 Players,28.4,10,5,0.667,3.21,16,16.0,15.0,...,0,4,587,1.168,7.6,1.0,3.0,7.5,2.53,NaN

In [5]:
F_1B = dfs[2]
#F_1B.rename(columns={ F_1B.columns[0]: "First Base" }, inplace = True)
F_1B.loc[-1] = ["First Base",np.NaN ,np.NaN ,np.NaN ,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]
#F_1B.loc[0] = F_1B.style.apply('font-weight : bold')
F_1B = F_1B.sort_index(ascending=True)
F_1B

                 Name     G     PO    A    E   DP   Fld%  RF/G  Notes
-1         First Base   NaN    NaN  NaN  NaN  NaN    NaN   NaN    NaN
 0  Hiroyuki Nakajima  14.0  111.0  7.0  1.0  8.0  0.992  8.43    NaN
 1         Daikan Yoh   6.0   26.0  3.0  0.0  1.0  1.000  4.83    NaN
 2    Takumi Kitamura   3.0   14.0  0.0  0.0  1.0  1.000  4.67    NaN
 3      Shunta Tanaka   2.0    5.0  0.0  0.0  1.0  1.000  2.50    NaN

In [6]:
F_2B = dfs[3]
#F_2B.rename(columns={ F_2B.columns[0]: "Second Base" }, inplace = True)
F_2B.loc[-1] = ["Second Base",np.NaN ,np.NaN ,np.NaN  ,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]
F_2B = F_2B.sort_index(ascending=True)
F_2B

                   Name     G    PO     A    E   DP  Fld%  RF/G  Notes
-1          Second Base   NaN   NaN   NaN  NaN  NaN   NaN   NaN    NaN
 0      Naoki Yoshikawa  15.0  18.0  21.0  0.0  5.0   1.0  2.60    NaN
 1      Takumi Kitamura   6.0  10.0  10.0  0.0  4.0   1.0  3.33    NaN
 2         Daiki Masuda   5.0   7.0  12.0  0.0  1.0   1.0  3.80    NaN
 3        Shunta Tanaka   1.0   0.0   3.0  0.0  0.0   1.0  3.00    NaN
 4  Akihiro Wakabayashi   1.0   1.0   3.0  0.0  1.0   1.0  4.00    NaN
 5            Dai Yuasa   1.0   0.0   0.0  0.0  0.0   NaN  0.00    NaN

In [7]:
F_3B = dfs[4]
#F_3B.rename(columns={ F_3B.columns[0]: "Third Base" }, inplace = True)
F_3B.loc[-1] = ["Third Base",np.NaN ,np.NaN ,np.NaN  ,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]
F_3B = F_3B.sort_index(ascending=True)
F_3B

                   Name     G    PO     A    E   DP  Fld%  RF/G  Notes
-1           Third Base   NaN   NaN   NaN  NaN  NaN   NaN   NaN    NaN
 0       Kazuma Okamoto  16.0  15.0  34.0  1.0  2.0  0.98  3.06    NaN
 1         Daiki Masuda   1.0   0.0   0.0  0.0  0.0   NaN  0.00    NaN
 2  Akihiro Wakabayashi   1.0   0.0   0.0  0.0  0.0   NaN  0.00    NaN

In [8]:
F_SS = dfs[5]
#F_SS.rename(columns={ F_SS.columns[0]: "Short Stop" }, inplace = True)
F_SS.loc[-1] = ["Short Stop",np.NaN ,np.NaN ,np.NaN  ,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]
F_SS = F_SS.sort_index(ascending=True)
F_SS

               Name     G    PO     A    E   DP  Fld%  RF/G  Notes
-1       Short Stop   NaN   NaN   NaN  NaN  NaN   NaN   NaN    NaN
 0  Hayato Sakamoto  15.0  25.0  43.0  0.0  8.0   1.0  4.53    NaN
 1     Daiki Masuda   5.0   1.0   5.0  0.0  0.0   1.0  1.20    NaN
 2    Shunta Tanaka   1.0   1.0   1.0  0.0  0.0   1.0  2.00    NaN
 3        Dai Yuasa   1.0   0.0   0.0  0.0  0.0   NaN  0.00    NaN

In [9]:
F_OF = dfs[6]
#F_OF.rename(columns={ F_OF.columns[0]: "Outfield" }, inplace = True)
F_OF.loc[-1] = ["Outfield",np.NaN ,np.NaN ,np.NaN  ,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]
F_OF = F_OF.sort_index(ascending=True)
F_OF

                    Name     G    PO    A    E   DP  Fld%  RF/G  Notes
-1              Outfield   NaN   NaN  NaN  NaN  NaN   NaN   NaN    NaN
 0        Yoshihiro Maru  16.0  29.0  1.0  0.0  0.0   1.0  1.88    NaN
 1         Gerardo Parra  15.0  15.0  0.0  0.0  0.0   1.0  1.00    NaN
 2       Yoshiyuki Kamei  11.0  12.0  0.0  0.0  0.0   1.0  1.09    NaN
 3  Shinnosuke Shigenobu  10.0   5.0  0.0  0.0  0.0   1.0  0.50    NaN
 4            Daikan Yoh   8.0   4.0  0.0  0.0  0.0   1.0  0.50    NaN
 5   Akihiro Wakabayashi   5.0   3.0  0.0  0.0  0.0   1.0  0.60    NaN
 6       Shingo Ishikawa   4.0   0.0  0.0  0.0  0.0   NaN  0.00    NaN
 7        Zelous Wheeler   4.0   4.0  0.0  0.0  0.0   1.0  1.00    NaN
 8          Daiki Masuda   3.0   0.0  0.0  0.0  0.0   NaN  0.00    NaN

In [10]:
F_Pitch = dfs[7]
#F_Pitch.rename(columns={ F_Pitch.columns[0]: "Pitching" }, inplace = True)
F_Pitch.loc[-1] = ["Pitching",np.NaN ,np.NaN ,np.NaN  ,np.NaN,np.NaN,np.NaN,np.NaN,np.NaN]
F_Pitch = F_Pitch.sort_index(ascending=True)
F_Pitch

                      Name     G   PO    A    E   DP  Fld%  RF/G  Notes
-1                Pitching   NaN  NaN  NaN  NaN  NaN   NaN   NaN    NaN
 0          Kyosuke Takagi  10.0  0.0  2.0  0.0  0.0   1.0  0.20    NaN
 1       Hirokazu Sawamura   8.0  1.0  1.0  0.0  0.0   1.0  0.25    NaN
 2            Yohei Kagiya   7.0  1.0  0.0  0.0  0.0   1.0  0.14    NaN
 3           Kota Nakagawa   7.0  0.0  2.0  0.0  0.0   1.0  0.29    NaN
 4        Rubby De La Rosa   6.0  1.0  0.0  0.0  0.0   1.0  0.17    NaN
 5        Takahiro Fujioka   6.0  0.0  2.0  0.0  0.0   1.0  0.33    NaN
 6        Ryosuke Miyaguni   6.0  1.0  0.0  0.0  0.0   1.0  0.17    NaN
 7         Takuya Kuwahara   4.0  0.0  4.0  0.0  1.0   1.0  1.00    NaN
 8   Cristopher Crisostomo   3.0  0.0  4.0  0.0  0.0   1.0  1.33    NaN
 9           Angel Sanchez   3.0  0.0  2.0  0.0  0.0   1.0  0.67    NaN
 10        Tomoyuki Sugano   3.0  2.0  1.0  0.0  0.0   1.0  1.00    NaN
 11         Kazuto Taguchi   3.0  0.0  1.0  0.0  0.0   1.0  0.33    NaN
 12        Toshiki Sakurai   2.0  0.0  2.0  0.0  0.0   1.0  1.00    NaN
 13            Shosei Togo   2.0  0.0  1.0  0.0  0.0   1.0  0.50    NaN
 14          Thyago Vieira   2.0  0.0  1.0  0.0  0.0   1.0  0.50    NaN
 15          Yuri Furukawa   1.0  0.0  0.0  0.0  0.0   NaN  0.00    NaN
 16         Hayato Horioka   1.0  0.0  0.0  0.0  0.0   NaN  0.00    NaN

In [11]:
Fielding1 = pandas.concat([F_1B, F_2B,F_3B,F_SS, F_OF, F_Pitch], axis=1, sort=False)
Fielding1

,Name,G,PO,A,E,DP,Fld%,RF/G,Notes,Name,...,Notes,Name,G,PO,A,E,DP,Fld%,RF/G,Notes
-1,First Base,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Second Base,...,NaN,Pitching,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Hiroyuki Nakajima,14.0,111.0,7.0,1.0,8.0,0.992,8.43,NaN,Naoki Yoshikawa,...,NaN,Kyosuke Takagi,10.0,0.0,2.0,0.0,0.0,1.0,0.20,NaN
1,Daikan Yoh,6.0,26.0,3.0,0.0,1.0,1.000,4.83,NaN,Takumi Kitamura,...,NaN,Hirokazu Sawamura,8.0,1.0,1.0,0.0,0.0,1.0,0.25,NaN
2,Takumi Kitamura,3.0,14.0,0.0,0.0,1.0,1.000,4.67,NaN,Daiki Masuda,...,NaN,Yohei Kagiya,7.0,1.0,0.0,0.0,0.0,1.0,0.14,NaN
3,Shunta Tanaka,2.0,5.0,0.0,0.0,1.0,1.000,2.50,NaN,Shunta Tanaka,...,NaN,Kota Nakagawa,7.0,0.0,2.0,0.0,0.0,1.0,0.29,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Akihiro Wakabayashi,...,NaN,Rubby De La Rosa,6.0,1.0,0.0,0.0,0.0,1.0,0.17,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dai Yuasa,...,NaN,Takahiro Fujioka,6.0,0.0,2.0,0.0,0.0,1.0,0.33,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Ryosuke Miyaguni,6.0,1.0,0.0,0.0,0.0,1.0,0.17,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Takuya Kuwahara,4.0,0.0,4.0,0.0,1.0,1.0,1.00,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Cristopher Crisostomo,3.0,0.0,4.0,0.0,0.0,1.0,1.33,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Angel Sanchez,3.0,0.0,2.0,0.0,0.0,1.0,0.67,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Tomoyuki Sugano,3.0,2.0,1.0,0.0,0.0,1.0,1.00,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Kazuto Taguchi,3.0,0.0,1.0,0.0,0.0,1.0,0.33,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Toshiki Sakurai,2.0,0.0,2.0,0.0,0.0,1.0,1.00,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Shosei Togo,2.0,0.0,1.0,0.0,0.0,1.0,0.50,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Thyago Vieira,2.0,0.0,1.0,0.0,0.0,1.0,0.50,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Yuri Furukawa,1.0,0.0,0.0,0.0,0.0,NaN,0.00,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,Hayato Horioka,1.0,0.0,0.0,0.0,0.0,NaN,0.00,NaN

In [12]:
Fielding = F_1B.append([F_2B,F_3B,F_SS, F_OF, F_Pitch])

In [ ]:
Fielding

In [687]:
# Export data

# https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html
Fielding.to_csv(path_or_buf="/Users/Anzo/Desktop/Fielding.csv")